language: generic
sudo: required
services:
 - docker
before_install:
 - docker build -t hereisvishal/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true hereisvishal/react-test npm test

after_success:
 - docker build -t hereisvishal/multi-client ./client
 - docker build -t hereisvishal/multi-server ./server
 - docker build -t hereisvishal/multi-nginx ./nginx
 - docker build -t hereisvishal/multi-worker ./worker
 